export const action = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FECTHING",
    DATA_FECTHED: "PROFILE_DATA_FECTHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
};
